services:
  mariadb:
    build:
      context: ./requirements/mariadb

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    networks:
      - inception

    volumes:
      - db_data:/var/lib/mysql
    
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_ADMIN_USER} -p${MYSQL_ADMIN_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    restart: always
  
  nginx:
    build:
      context: ./requirements/nginx

    ports:
      - "443:443"

    networks:
      - inception

    volumes:
      - wordpress:/var/www/html
    
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress

    environment:
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_EMAIL: ${WORDPRESS_DB_EMAIL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}

    networks:
      - inception

    volumes:
      - wordpress:/var/www/html

    depends_on:
      mariadb:
        condition: service_healthy
      

    #restart: always

networks:
  inception:
    name: inception
    driver: bridge

# secrets:
#   mysql_admin_user:
#     file: ../secrets/mysql_admin_user
#   mysql_admin_pass:
#     file: ../secrets/mysql_admin_pass
#   mysql_user:
#     file: ../secrets/mysql_user
#   mysql_pass:
#     file: ../secrets/mysql_pass
#   mysql_root_password:
#     file: ../secrets/mysql_root_password

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/helferna/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/helferna/data/wordpress
      o: bind

  

    