services:
  db:
    build:
      context: ./requirements/mariadb

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    networks:
      - inception

    volumes:
      - db_data:/var/lib/mysql
    
    restart: always
  
  nginx:
    build:
      context: ./requirements/nginx

    ports:
      - "443:443"

    networks:
      - inception

    volumes:
      - wordpress:/var/www/html
    
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

    networks:
      - inception

    volumes:
      - wordpress:/var/www/html

    restart: always

networks:
  inception:
    name: inception
    driver: bridge

# secrets:
#   mysql_admin_user:
#     file: ../secrets/mysql_admin_user
#   mysql_admin_pass:
#     file: ../secrets/mysql_admin_pass
#   mysql_user:
#     file: ../secrets/mysql_user
#   mysql_pass:
#     file: ../secrets/mysql_pass
#   mysql_root_password:
#     file: ../secrets/mysql_root_password

volumes:
  db_data:
  wordpress:

  

    