services:
  mariadb:
    build:
      labels:
        - mariadb
      context: ./requirements/mariadb

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    networks:
      - inception

    volumes:
      - db_data:/var/lib/mysql
    
    restart: always
  
  nginx:
    build:
      labels:
        - nginx
      context: ./requirements/nginx

    ports:
      - "443:443"

    networks:
      - inception

    volumes:
      - wordpress:/var/www/html

    depends_on:
      - wordpress
    
    restart: always
  
  wordpress:
    build:
      labels:
          - wordpress
      context: ./requirements/wordpress

    environment:
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_EMAIL: ${WORDPRESS_DB_EMAIL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_USER_ONE_EMAIL: ${WORDPRESS_USER_ONE_EMAIL}
      WORDPRESS_USER_ONE_PASSWORD: ${WORDPRESS_USER_ONE_PASSWORD}
      WORDPRESS_USER_ONE: ${WORDPRESS_USER_ONE}

    networks:
      - inception

    volumes:
      - wordpress:/var/www/html

    depends_on:
      - mariadb
      
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/helferna/data/mariadb
      o: bind
  
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/helferna/data/wordpress
      o: bind

  

    