FROM debian:11

# Install Nginx
RUN apt-get update -y && apt-get install -y nginx

# Copy the configuration file


# Copy the script to create the database and configure the database


# Run the script


# Expose the port
EXPOSE 80